Repository Dining-together/Algorithm-study, pull requests merged in 2021-10, with the labels that each got.

#16 2021-09-30
  yunva17/그리디/설탕배달.py
  yunva17/그리디/전자레인지.py
Labels: BOJ, Python

#17 2021-10-01
  README.md
  계획/구현.md
  신태범/1. 그리디/BOJ_13305.py
  신태범/1. 그리디/BOJ_13305_2.py
  신태범/1. 그리디/BOJ_1543.py
  신태범/1. 그리디/BOJ_2847.py
Labels: docs, BOJ, Python

#18 2021-10-01
  jifrozen/그리디/11047.java
  jifrozen/그리디/1541.java
Labels: BOJ, Java

#20 2021-10-01
  yunva17/그리디/수들의_합.py
  yunva17/그리디/이장님_초대.py
Labels: BOJ, Python

#21 2021-10-01
  yejipractice/BOJ/그리디/동전_0.py
  yejipractice/BOJ/그리디/잃어버린_괄호.py
Labels: BOJ, Python

#24 2021-10-04
  신태범/2.구현/게임개발.py
  신태범/2.구현/상하좌우.py
  신태범/2.구현/상하좌우_2.py
  신태범/2.구현/시각.py
  신태범/2.구현/왕실의_나이트.py
Labels: 이코테, Python

#23 2021-10-04
  jifrozen/구현/게임_개발.java
  jifrozen/구현/상하좌우.java
  jifrozen/구현/시각.java
  jifrozen/구현/왕실의_나이트.java
Labels: 이코테, Java

#25 2021-10-05
  신태범/2.구현/럭키_스트레이트.py
  신태범/2.구현/문자열_압축.py
  신태범/2.구현/문자열_재정렬.py
Labels: 이코테, Python

#26 2021-10-04
  yunva17/구현/게임_개발.md
  yunva17/구현/상하좌우.py
  yunva17/구현/시각.py
  yunva17/구현/왕실의_나이트.py
Labels: 이코테, Python

#27 2021-10-04
  README.md
  yejipractice/이코테/구현/게임_개발.py
  yejipractice/이코테/구현/구현.md
  yejipractice/이코테/구현/상하좌우.py
  yejipractice/이코테/구현/시각.py
  yejipractice/이코테/구현/왕실의_나이트.py
  계획/구현.md
Labels: 이코테, Python

#28 2021-10-06
  신태범/2.구현/기둥과_보_설치.py
  신태범/2.구현/뱀.py
  신태범/2.구현/자물쇠와_열쇠.py
Labels: 이코테, Python

#29 2021-10-05
  yejipractice/이코테/구현/럭키_스트레이트.py
  yejipractice/이코테/구현/문자열_압축.py
  yejipractice/이코테/구현/문자열_재정렬.py
Labels: 이코테, Python

#30 2021-10-05
  yunva17/구현/럭키_스트레이트.py
  yunva17/구현/문자열_압축.py
  yunva17/구현/문자열_재정렬.py
Labels: 이코테, Python

#31 2021-10-05
  jifrozen/구현/럭키_스트레이트.java
  jifrozen/구현/문자열_압축.java
  jifrozen/구현/뱀.java
Labels: 이코테, Java

#36 2021-10-08
  yejipractice/BOJ/구현/로봇_청소기.py
  yejipractice/PRG/구현/신규_아이디_추천.py
Labels: BOJ, Programmers, Python

#37 2021-10-08
  신태범/2.구현/결혼식.py
  신태범/2.구현/톱니바퀴.py
Labels: BOJ, Python

#38 2021-10-07 && 2021-10-08
  jifrozen/구현/기둥과_보_설치.java
  jifrozen/구현/기둥과_보_설치2.java
  jifrozen/구현/로봇_청소기.java
  jifrozen/구현/신규_아이디_추천.java
  jifrozen/구현/외벽점검.java
Labels: 이코테, BOJ, Programmers, Java

#41 2021-10-11
  신태범/4. 정렬/두_배열의_원소_교체.py
  신태범/4. 정렬/성적이_낮은_순서로_학생_출력하기.py
  신태범/4. 정렬/위에서_아래로.py
Labels: 이코테, Python

#49 2021-10-13
  jifrozen/정렬/k번째수.java
  jifrozen/정렬/회의실_배정.java
Labels: BOJ, Programmers, Java

#50 2021-10-13
  yejipractice/BOJ/정렬/회의실_배정.py
  yejipractice/PRG/정렬/K번째수.py
Labels: 이코테, Programmers, Python

#51 2021-10-14
  jifrozen/정렬/ATM.java
  jifrozen/정렬/가장_큰_수.java
Labels: BOJ, Programmers, Java

#53 2021-10-15
  yejipractice/BOJ/정렬/전화번호_목록.py
  yejipractice/PRG/정렬/H-Index.py
Labels: BOJ, Programmers, Python

#54 Merge from yejipractice to main
  yejipractice/BOJ/정렬/ATM.py
  yejipractice/BOJ/정렬/전화번호_목록.py
  yejipractice/BOJ/정렬/회의실_배정.py
  yejipractice/PRG/정렬/H-Index.py
  yejipractice/PRG/정렬/K번째수.py
  yejipractice/PRG/정렬/가장_큰_수.py
  yejipractice/이코테/정렬/국영수.py
  yejipractice/이코테/정렬/두_배열의_원소_교체.py
  yejipractice/이코테/정렬/성적이_낮은_순서로_학생_출력하기.py
  yejipractice/이코테/정렬/실패율.py
  yejipractice/이코테/정렬/안테나.py
  yejipractice/이코테/정렬/위에서_아래로.py
  yejipractice/이코테/정렬/정렬.md
  yejipractice/이코테/정렬/카드_정렬하기.py
Labels: merge

#56 2021-10-15
  jifrozen/정렬/H_index.java
  jifrozen/정렬/전화번호_목록.java
Labels: BOJ, Programmers, Java

#58 2021-10-12
  yunva17/정렬/국영수.py
  yunva17/정렬/실패율.py
  yunva17/정렬/안테나.py
  yunva17/정렬/카드_정렬하기.py
Labels: 이코테, Python

#59 2021-10-13
  yunva17/정렬/나이순_정렬.py
  yunva17/정렬/소트인사이드.py
Labels: BOJ, Python

#64 2021-10-19
  jifrozen/DFS_BFS/경쟁적_전염.java
  jifrozen/DFS_BFS/연구소.java
  jifrozen/DFS_BFS/특정_거리의_도시_찾기.java
Labels: 이코테, Java

#92 2021-10-26~2021-10-29
  yunva17/이진탐색/가사_검색.py
  yunva17/이진탐색/고정점_찾기.py
  yunva17/이진탐색/공유기_설치.py
  yunva17/이진탐색/나무_자르기.py
  yunva17/이진탐색/수_찾기.py
  yunva17/이진탐색/숫자_카드.py
  yunva17/이진탐색/입국_심사.py
  yunva17/이진탐색/정렬된_배열에서_특정_수의_개수_구하기.py
Labels: 이코테, BOJ, Python

#93 Merge from yejipractice to main
  yejipractice/BOJ/이진탐색/K번째_수.py
  yejipractice/BOJ/이진탐색/기타_레슨.py
  yejipractice/BOJ/이진탐색/나무_자르기.py
  yejipractice/PRG/이진탐색/입국심사.py
  yejipractice/이코테/이진탐색/가사_검색.py
  yejipractice/이코테/이진탐색/고정점_찾기.py
  yejipractice/이코테/이진탐색/공유기_설치.py
  yejipractice/이코테/이진탐색/떡볶이_떡_만들기.py
  yejipractice/이코테/이진탐색/부품_찾기.py
  yejipractice/이코테/이진탐색/이진탐색.md
  yejipractice/이코테/이진탐색/정렬된_배열에서_특정_수의_개수_구하기1.py
  yejipractice/이코테/이진탐색/정렬된_배열에서_특정_수의_개수_구하기2.py
Labels: merge

#94 [Docs] 6주차 문서추가
  README.md
  계획/다이나믹_프로그래밍.md
Labels: docs, merge
