Repository Dining-together/Algorithm-study, pull requests merged in 2021-09, with the labels that each got.

#1 2021-09-27
  yejipractice/이코테/그리디/1이_될_때까지.py
  yejipractice/이코테/그리디/거스름돈.py
  yejipractice/이코테/그리디/그리디.md
  yejipractice/이코테/그리디/숫자_카드_게임.py
  yejipractice/이코테/그리디/큰_수의_법칙.py
Labels: 이코테, Python

#2 2021-09-27
  jifrozen/그리디/1이_될_때까지.java
  jifrozen/그리디/거스름돈.java
  jifrozen/그리디/숫자_카드_게임.java
  jifrozen/그리디/큰_수의_법칙.java
Labels: 이코테, Java

#3 2021-09-27
  신태범/1. 그리디/1이_될_때까지.py
  신태범/1. 그리디/거스름돈.py
  신태범/1. 그리디/숫자_카드_게임.py
  신태범/1. 그리디/큰_수의_법칙.py
Labels: 이코테, Python

#4 2021-09-27
  yunva17/그리디/1이_될_때까지.py
  yunva17/그리디/거스름돈.py
  yunva17/그리디/숫자_카드_게임.py
  yunva17/그리디/큰_수의_법칙.py
Labels: 이코테, Python

#6 2021-09-28
  신태범/1. 그리디/곱하기_혹은_더하기.py
  신태범/1. 그리디/모험가_길드.py
  신태범/1. 그리디/모험가_길드_2.py
  신태범/1. 그리디/문자열_뒤집기.py
Labels: 이코테, Python

#7 2021-09-28
  jifrozen/그리디/곱하기_혹은_더하기.java
  jifrozen/그리디/모험가_길드.java
  jifrozen/그리디/문자열_뒤집기.java
Labels: 이코테, Java

#8 2021-09-28
  yejipractice/이코테/그리디/곱하기_혹은_더하기.py
  yejipractice/이코테/그리디/모험가_길드.py
  yejipractice/이코테/그리디/문자열_뒤집기.py
Labels: 이코테, Python

#9 2021-09-28
  yunva17/그리디/곱하기_혹은_더하기.py
  yunva17/그리디/모험가_길드.py
  yunva17/그리디/문자열_뒤집기.py
Labels: 이코테, Python

#10 2021-09-29
  신태범/1. 그리디/BOJ_1339.py
  신태범/1. 그리디/BOJ_1700.py
  신태범/1. 그리디/BOJ_1744.py
  신태범/1. 그리디/BOJ_1744_2.py
  신태범/1. 그리디/만들_수_없는_금액.py
  신태범/1. 그리디/무지의_먹방_라이브.py
  신태범/1. 그리디/무지의_먹방_라이브_2.py
  신태범/1. 그리디/볼링공_고르기.py
Labels: 이코테, Python

#11 2021-09-29
  yejipractice/이코테/그리디/만들_수_없는_금액.py
  yejipractice/이코테/그리디/무지의_먹방_라이브.py
  yejipractice/이코테/그리디/볼링공_고르기.py
Labels: 이코테, Python

#13 2021-09-29
  yunva17/그리디/만들_수_없는_금액.py
  yunva17/그리디/무지의_먹방_라이브.py
  yunva17/그리디/볼링공_고르기.py
Labels: 이코테, Python

#12 2021-09-29
  jifrozen/그리디/만들_수_없는_금액.java
  jifrozen/그리디/무지의_먹방_라이브.java
  jifrozen/그리디/무지의_먹방_라이브.py
  jifrozen/그리디/무지의_먹방_라이브3.java
  jifrozen/그리디/볼링공_고르기.java
Labels: 이코테, Java, Python

#14 2021-09-30
  yejipractice/BOJ/그리디/수_묶기.py
  yejipractice/BOJ/그리디/캠핑.py
Labels: BOJ, Python

#15 2021-09-30
  jifrozen/그리디/1744.java
  jifrozen/그리디/4796.java
Labels: BOJ, Java
